name: Auto Generate qxy_icons.json

on:
  push:
    paths:
      - 'icon/**' 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 显示目录结构（调试用，可移除）
        run: ls -R

      - name: 执行生成 JSON 脚本
        run: python .github/generate_json.py  

      - name: 提交并推送更新（如果有变化）
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add qxy_icons.json

          # 仅当文件有变更时才提交
          if ! git diff --cached --quiet; then
            git commit -m "自动更新 qxy_icons.json"
            git push
          else
            echo "无变化，跳过提交。"
          fi
